name: CI-CD to My Machine
on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
    # ขั้นตอนที่ 1: ดึงโค้ดลงเครื่อง (ใส่สคริปต์บังคับให้ใช้สิทธิ์ตามปกติ)
    - name: Checkout Code
      uses: actions/checkout@v4

    # ขั้นตอนที่ 2: ใช้คำสั่ง echo แบบง่ายที่สุดพิมพ์ข้อความทดสอบ
    - name: Test Running Command
      shell: cmd
      run: echo GitHub Actions is working fine on my Windows machine!